[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "queso"
version = "0.0.0"
requires-python = ">=3.9"
dependencies = [
    "h5py",
    "matplotlib",
    "polars",
    "numpy",
    "jax",
    "torch",
    "optax",
]
