folder: null
seed: null

train_circuit: True
sample_circuit: True
train_nn: True
benchmark_estimator: True

n: 4
k: 4

preparation: 'brick_wall_cr'
interaction: 'local_rx'
detection: 'local_r'
backend: 'ket'

# training circuit args
n_phis: 100
n_steps: 20000
lr_circ: 1e-3
phi_range: [-1.0, 1.0]

# sample circuit args
n_shots: 5000
n_shots_test: 1000

# train estimator args
n_epochs: 1000
batch_size: 50
n_grid: 100  # todo: make more general - not requiring matching training phis and grid
nn_dims: [32, 32]
lr_nn: 1e-3
from_checkpoint: false

# benchmark estimator args
n_trials: int = 100
phis_inds: [50]
n_sequences: [1, 10, 100, 1000]


